export const AllCalculators = [
  "EMI calculator",
  "Home Loan EMI calculator",
  "Car Loan EMI Calculator",
  "Simple Interest Calculator",
  "Compound Interest Calculator",
  "Mutual Funds Calculator",
  "Lumpsum Calculator",
  "SIP Calculator",
  "Fixed Deposit Calculator",
  "Recurring Deposit Calculator",
  "Flat Interest Calculator",
  "CAGR Calculator",
  "Inflation Calculator",
  "Gratuity Calculator",
  "PPF Calculator",
  "GST Calculator",
  "NPS Calculator",
  "SSY Calculator",
  "NSC Calculator",
];
